### ISSUE TITLE
Performance bogs down with normal web use.

### ISSUE THREAD

**Issue by Mitch0S** [synchronizing/mitm#18]
G'day,

I tried using the proxy as a normal HTTPs proxy for normal web-browsing. It seems like it struggles with a backlog of requests and does things sequentially.

I'm not sure if it's built for this kind of purpose, but it's what I intend on using it for so any help in getting it to run slightly smoother would be of great help!

Cheers,

Mitch

**Comment by Mitch0S** [comment]
Regarding the version of `mitm`, I am currently using `v1.3.0`

Yeah, I haven't looked too far into the `mitm` stack, but If I have some free time over this coming up holidays, I'll take a look into how `mitmproxy` handles connections/requests and see if that can be of any help :)

Cheers!

**Comment by synchronizing** [comment]
Added #19 to mitigate bottle neck issues. `v1.3` was/is improperly using `lru_cache` to do the caching, but `v1.4` will fix it. I also recommend to turn off logging, as this will improve performance. 

Browsed and used WhatsApp for about an hour with #19 enabled, and had zero issues. Things seem to work as expected. Give `v1.4` a try and lmk! Closing this for the meantime.
