### ISSUE TITLE
Use without having to use verify=False

### ISSUE THREAD

**Issue by Zorkai** [synchronizing/mitm#3]
Hello, I wanted to know if it was possible to use this project without having to use verify=False.
I heard this was possible by installing a certificate. 
Not using verify=False while doing requests will make my program crash because of SSL errors

**Comment by synchronizing** [comment]
You are indeed right: `verify=False` needs to be set to essentially tell requests to trust the bogus certificate that `mitm` generates to create a TLS/SSL connection with the client. 

To give a little bit of context, computers are shipped with certificates (public keys) that are signed by [certificate authorities](https://en.wikipedia.org/wiki/Certificate_authority) (CA). These CAs hold huge events where they generate the private key and certificates, and make a huge effort to make sure the private keys are secure. If a private key leaks people can then intercept SSL/TLS traffic at will.

Therefore, to not use `verify=False` you need to install the certificate on your computer. To do this, there is three specific settings within `mitm.Config` to allow you to generate the certificate outside of your data folder:

```python
from mitm import Config
import pathlib

dt = pathlib.Path.home() / "Desktop"
config = Config(rsa_key=dt / "mitm.key", rsa_cert=dt / "mitm.crt", rsa_generate=True)
```

The above code should generate two files on your desktop, `mitm.key` and `mitm.crt`. The `.key` file is the private key, and the `.crt` file is the certificate. The certificate is what you want to install. Depending on platform (Win, Mac, Linux) there are different steps for installing it - whatever the case, once you do install it (and make sure to set trust settings), you will no longer need to set request's `verify=` flag.  Do remember to load the certificates the next time you boot-up `mitm`, and set `rsa_generate=False`.

Note, however, that installing certificates like these open your computer to future dangers as anyone with the `.key` file can then use that to decipher your internet traffic. Another (less invasive) way to not have to set `verify=` in requests is by using the `REQUESTS_CA_BUNDLE` env variable (see [here](https://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification)). Simply doing:

```python
export REQUESTS_CA_BUNDLE=/path/to/your/certificate.crt
python script.py
```

Should be enough. Hopefully that helps!

**Comment by synchronizing** [comment]
Oh, also - you can generate your own custom certificates if you would like. Take a look at:

https://github.com/synchronizing/mitm/blob/b53efea3a4d8d120d5462da5a298ecc287cafc29/mitm/crypto.py#L12-L21

https://github.com/synchronizing/mitm/blob/b53efea3a4d8d120d5462da5a298ecc287cafc29/mitm/crypto.py#L29-L58

https://github.com/synchronizing/mitm/blob/b53efea3a4d8d120d5462da5a298ecc287cafc29/mitm/crypto.py#L74-L81

`new_pair` is what `mitm` uses to generate the cert. You can generate your own, and then load it into `mitm`.

**Comment by synchronizing** [comment]
Let me know if anything else. Closing this for now.

**Comment by Zorkai** [comment]
This doesn't seem to work on windows. After installing the certificate, I'm getting `[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate`

Code :
```py
import requests
proxies = {"http": "http://127.0.0.1:8888", "https": "https://127.0.0.1:8888"}
requests.get("https://google.com", proxies=proxies)

**Comment by synchronizing** [comment]
Reopening issue to continue discussion. 

On Windows, you'll likely have to install the certificate, _and_ set trust settings. The Google query should be "windows trust self-signed certificate" - perhaps [this](https://www.ntweekly.com/2020/08/31/make-a-self-signed-certificate-trusted-on-windows/) might work?

**Comment by Zorkai** [comment]
That's how I initially did it. It doesn't work for some reason.

**Comment by synchronizing** [comment]
It should work in theory work. I don't know if there is anything else I can do to help 😕

**Comment by Zorkai** [comment]
And this works on Mac / Linux?

**Comment by synchronizing** [comment]
In theory it should work in all systems.

**Comment by synchronizing** [comment]
> > In theory it should work in all systems.
> 
> Hey. I'm also trying this. Going through the code, it seems like mitm creates only one certificate. What should be happening is, mitm should create a separate certificate for every domain using the CA certificate it generates right now.
> 
> Right now even by using the generated certificate for verification, the request will fail:
> 
> ```
> ➜  ~ curl -x 127.0.0.1:8888 https://google.com --cacert ~/Library/Application\ Support/mitm/mitm.crt
> curl: (60) SSL: certificate subject name 'MBP-H744TTW0YW' does not match target host name 'google.com'
> ```
> 
> Note how it expects the certificate sent by the proxy subject to be google.com but it isn't. The proxy is just sending the CA certificate instead of a google.com one.
> 
> I might be wrong about something here. Let me know what you think.

You are indeed right. I made a note of it [here](https://github.com/synchronizing/mitm/issues/11#issuecomment-1119687064) and will be pushing a patch up soon. 😄
